name: Go Test Runner

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set working directory
      run: cd score-server
      shell: bash

    - name: Get dependencies
      run: |
        go mod download
        go mod verify
      working-directory: ./score-server

    - name: Run tests
      run: go test ./...
      working-directory: ./score-server
      env:
        GO111MODULE: on
